import { Workbook } from "@oai/artifact-tool";
const wb=Workbook.create();
console.log(Object.keys(wb));
console.log(wb.worksheets);
console.log(typeof wb.worksheets.add);
const s=wb.worksheets.add('Test');
console.log(Object.keys(s).slice(0,50));
console.log(typeof s.getRange);
const r=s.getRange('A1:B2');
console.log(Object.keys(r).slice(0,80));
console.log(typeof r.values);
